apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: rlcatalyst   #Replace with your namespace
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ec2-user/logs"
    type: "DirectoryOrCreate"
