AWSTemplateFormatVersion: 2010-09-09

Description: Sets up RStudio environment on AWS

Parameters:
  InstanceType:
    Type: String
    Description: Instance type for RStudio. Default is t2.medium.
    AllowedValues:
      - t2.medium
      - t2.large
      - t2.xlarge
      - m4.xlarge
      - c4.xlarge
      - r4.xlarge
      - r4.xlarge
      - p2.xlarge
      
    ConstraintDescription: Valid instance type in the t2 families
    Default: t2.medium
  InitialUser:
    Type: String
    Description: User Name for RStudio. Do not use 'root' and 'ec2-user'
    Default: rstudio
  InitialPassword:
    Type: String
    Description: Password for RStudio. Please keep in your records as this will not be echoed in the CloudFormation Console
    NoEcho: True
  KeyPair:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance. If no key pairs exist, please create one from the button next to the dropdown. Please contact your Administrator if you are unable to create one.
  
Resources:
  RstudioEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp
        - CidrIp: "0.0.0.0/0"
          FromPort: 80
          ToPort: 80
          IpProtocol: tcp
        - CidrIp: "0.0.0.0/0"
          FromPort: 8787
          ToPort: 8787
          IpProtocol: tcp
      GroupDescription: RStudio and Shiny Security Group

  RstudioEC2Instance:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT9M
    Properties:
      ImageId : '{{resolve:ssm:/RL/RG/StandardCatalog/RStudio}}'
      InstanceType: !Ref 'InstanceType'
      SecurityGroups: [!Ref 'RstudioEC2SecurityGroup']
      KeyName: !Ref 'KeyPair'
      UserData: !Base64
      Tags:
      - Key: Name
        Value: !Join ["-", [!Ref "AWS::StackName", "RStudio"]]
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash 
          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
          trap '/opt/aws/bin/cfn-signal --exit-code 1 --resource RstudioEC2Instance --region ${AWS::Region} --stack ${AWS::StackName}' ERR
          #add user(s)
          sudo useradd -m -s /bin/bash ${InitialUser}
          sudo echo ${InitialUser}:${InitialPassword} | chpasswd
            /opt/aws/bin/cfn-signal --exit-code 0 --resource RstudioEC2Instance --region ${AWS::Region} --stack ${AWS::StackName}

Outputs:
  InstanceDNSName:
    Value: !GetAtt RstudioEC2Instance.PublicDnsName
    Description: Public DNS Name
  InstanceIPAddress: 
    Value: !GetAtt RstudioEC2Instance.PublicIp
  InstanceId:
    Value: !Ref 'RstudioEC2Instance'
  ApplicationPort:
    Value: '8787'